version: '3.8'
services:

  db:

    container_name: pg_container
    image: postgres:14-alpine
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"

  pgadmin:

    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    env_file: .env
    restart: always
    ports:
      - "5050:80"